# Generated by Django 5.1 on 2024-08-29 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_orderdetail_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="order_number",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="user",
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="orders.order",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
