# Generated by Django 5.1 on 2024-09-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_orderdetail_order_number_orderdetail_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "В ожидании"),
                    ("Shipped", "Отправлен"),
                    ("Delivered", "Доставлен"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
